export const ADD_STAFF='ADD_STAFF';

export const DELETE_STAFF_LOADING='DELETE_STAFF_LOADING';
export const DELETE_STAFF_SUCCESS='DELETE_STAFF_SUCCESS';

export const ADD_STAFFS='ADD_STAFFS';
export const STAFFS_LOADING='STAFFS_LOADING';
export const STAFFS_FAILED='STAFFS_FAILED';

export const ADD_DEPARTMENTS='ADD_DEPARTMENTS';
export const DEPARTMENTS_LOADING='DEPARTMENTS_LOADING';
export const DEPARTMENTS_FAILED='DEPARTMENTS_FAILED';

export const ADD_STAFFSALARY='ADD_STAFFSALARY';
export const STAFFSALARY_LOADING='STAFFSALARY_LOADING';
export const STAFFSALARY_FAILED='STAFFSALARY_FAILED';

export const UPDATE_STAFF='UPDATE_STAFF';
