export const ADD_STAFF='ADD_STAFF';
export const STAFF_LOADING='STAFF_LOADING';
export const STAFF_FAILED='STAFF_FAILED';

export const ADD_DEPARTMENT='ADD_DEPARTMENT';
export const DEPARTMENT_LOADING='DEPARTMENT_LOADING';
export const DEPARTMENT_FAILED='DEPARTMENT_FAILED';

export const ADD_SALARY='ADD_SALARY';
export const SALARY_LOADING='SALARY_LOADING';
export const SALARY_FAILED='SALARY_FAILED';

export const STAFFINDEPT_SALARY='ADD_STAFFINDEPT';
export const STAFFINDEPT_LOADING='STAFFINDEPT_LOADING';
export const STAFFINDEPT_FAILED='STAFFINDEPT_FAILED';